# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=75, verbose_name='E-mail')),
                ('twitter', models.URLField(verbose_name='Twitter')),
            ],
        ),
    ]
